/**
 * Frontend "build" script.
 *
 * This project is a plain static HTML/CSS/vanilla-JS site — there is no
 * bundler (no Vite/Webpack/etc). This script exists only to:
 *
 *   1. Read frontend/.env (if present) and regenerate js/config.js, so the
 *      backend URL can be configured per environment without hardcoding it
 *      inside application code (the closest static-site equivalent of a
 *      framework's build-time env injection).
 *   2. Copy the site into dist/ as the deployable output folder.
 *
 * It intentionally uses only Node's built-in modules — no dependencies
 * were added just to "build" a static site.
 */
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const DIST = path.join(ROOT, 'dist');

// -- 1. Load .env (simple KEY=VALUE parser, no dependency) ---------------
function loadEnv(filePath) {
  const env = {};
  if (!fs.existsSync(filePath)) return env;
  const lines = fs.readFileSync(filePath, 'utf8').split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    env[key] = value;
  }
  return env;
}

const envFile = fs.existsSync(path.join(ROOT, '.env'))
  ? path.join(ROOT, '.env')
  : path.join(ROOT, '.env.example');
const env = loadEnv(envFile);

// Precedence: a real environment variable (e.g. one set in the Vercel
// dashboard under Project Settings -> Environment Variables) wins over
// a checked-out .env file, which wins over .env.example's local-dev
// default. This is what lets the SAME repo build correctly for local
// dev (via frontend/.env, gitignored) and for a Vercel deployment (via
// an env var Vercel injects into process.env at build time) without
// committing an environment-specific URL into the repo.
const apiBaseUrl = process.env.API_BASE_URL || env.API_BASE_URL || 'http://localhost:5000';

// -- 2. Regenerate js/config.js -------------------------------------------
const configContent = `/**
 * Auto-generated by build.js from ${path.basename(envFile)}.
 * Do not edit by hand — edit frontend/.env and re-run "npm run build".
 */
window.APP_CONFIG = {
  API_BASE_URL: ${JSON.stringify(apiBaseUrl)}
};
`;
fs.writeFileSync(path.join(ROOT, 'js', 'config.js'), configContent);
console.log(`[build] wrote js/config.js (API_BASE_URL=${apiBaseUrl})`);

// -- 3. Copy everything into dist/ (excluding tooling/config files) -------
const EXCLUDE = new Set([
  'node_modules', 'dist', '.env', '.git', '.vercel', '.vscode',
  'build.js', 'package.json', 'package-lock.json', '.env.example'
]);

fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(DIST, { recursive: true });

for (const entry of fs.readdirSync(ROOT)) {
  if (EXCLUDE.has(entry)) continue;
  fs.cpSync(path.join(ROOT, entry), path.join(DIST, entry), { recursive: true });
}

console.log(`[build] copied static site into ${path.relative(ROOT, DIST)}/`);
